import React, { useState } from 'react';
import '@/css/Add.css'; // Ensure the path to CSS is correct

const Add = () => {
  const [museumId, setMuseumId] = useState(0);  // This will be auto-generated by the backend
  const [nama, setNama] = useState('');
  const [lokasi, setLokasi] = useState('');
  const [noTelpon, setNoTelpon] = useState('');
  const [keterangan, setKeterangan] = useState('');
  const [rating, setRating] = useState(0);
  const [jumlahTiket, setJumlahTiket] = useState(0);
  const [tiketRegulerPrice, setTiketRegulerPrice] = useState(0);
  const [tiketPelajarPrice, setTiketPelajarPrice] = useState(0);
  const [tiketKeluargaPrice, setTiketKeluargaPrice] = useState(0);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();

    const museumData = {
      museumId,
      nama,
      lokasi,
      noTelpon,
      keterangan,
      rating,
      jumlahTiket,
      tiketRegulerPrice,
      tiketPelajarPrice,
      tiketKeluargaPrice,
    };

    try {
      const response = await fetch('http://localhost:9090/admins/AddMuseum', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(museumData),
      });

      if (response.ok) {
        console.log('Museum added successfully');
        // Optionally, you can redirect the user or show a success message
      } else {
        console.error('Failed to add museum');
        // Handle error response from the backend
      }
    } catch (error) {
      console.error('Error:', error);
      // Handle network errors or other exceptions
    }
  };

  return (
    <div className="add-page">
      <div className="add-container">
        <div className="header">
          <div className="logo">
            Museum<span className="tix">Tix</span>
          </div>
          <h1>Add Museum</h1>
          <p>Masukkan informasi museum yang ingin ditambahkan</p>
        </div>
        <form onSubmit={handleSubmit}>
          <div className="form-group center">
            <label>Nama Museum:</label>
            <input
              type="text"
              value={nama}
              onChange={(e) => setNama(e.target.value)}
              required
            />
          </div>
          <div className="form-group left">
            <label>Lokasi Museum:</label>
            <input
              type="text"
              value={lokasi}
              onChange={(e) => setLokasi(e.target.value)}
              required
            />
          </div>
          <div className="form-group left">
            <label>No. Telpon Museum:</label>
            <input
              type="text"
              value={noTelpon}
              onChange={(e) => setNoTelpon(e.target.value)}
              required
            />
          </div>
          <div className="form-group left">
            <label>Keterangan Museum:</label>
            <textarea
              value={keterangan}
              onChange={(e) => setKeterangan(e.target.value)}
              required
            ></textarea>
          </div>
          <div className="form-row">
            <div className="form-group left">
              <label>Rating:</label>
              <input
                type="number"
                value={rating}
                onChange={(e) => setRating(Number(e.target.value))}
                required
                min="0"
                max="5"
                step="0.1"
                placeholder="e.g., 4.5"
              />
            </div>
            <div className="form-group left">
              <label>Jumlah Tiket:</label>
              <input
                type="number"
                value={jumlahTiket}
                onChange={(e) => setJumlahTiket(Number(e.target.value))}
                required
              />
            </div>
          </div>
          <div className="form-row">
            <div className="form-group left">
              <label>Harga Tiket Reguler:</label>
              <input
                type="number"
                value={tiketRegulerPrice}
                onChange={(e) => setTiketRegulerPrice(Number(e.target.value))}
                required
              />
            </div>
            <div className="form-group left">
              <label>Harga Tiket Pelajar:</label>
              <input
                type="number"
                value={tiketPelajarPrice}
                onChange={(e) => setTiketPelajarPrice(Number(e.target.value))}
                required
              />
            </div>
            <div className="form-group left">
              <label>Harga Tiket Keluarga:</label>
              <input
                type="number"
                value={tiketKeluargaPrice}
                onChange={(e) => setTiketKeluargaPrice(Number(e.target.value))}
                required
              />
            </div>
          </div>
          <div className="button-group">
            <button type="submit" className="add-button">Add</button>
            <button type="button" className="cancel-button">Cancel</button>
          </div>
        </form>
      </div>
    </div>
  );
};

export default Add;
