import React, { useState, useEffect } from 'react';
import '@/css/Edit.css'; // Ensure the path to CSS is correct
import { useRouter } from 'next/router';

const Edit = ({museum_id}) => {
  const [museumId, setMuseumId] = useState(0);  // This will be auto-generated by the backend
  const [nama, setNama] = useState('');
  const [lokasi, setLokasi] = useState('');
  const [noTelpon, setNoTelpon] = useState('');
  const [keterangan, setKeterangan] = useState('');
  const [rating, setRating] = useState(0);
  const [jumlahTiket, setJumlahTiket] = useState(0);
  const [tiketRegulerPrice, setTiketRegulerPrice] = useState(0);
  const [tiketPelajarPrice, setTiketPelajarPrice] = useState(0);
  const [tiketKeluargaPrice, setTiketKeluargaPrice] = useState(0);

  const [museum, setMuseum] = useState([]);

  useEffect(() => {
      if (museum_id) {
        setMuseumId(museum_id);  
      }
  }, []);

  useEffect(() => {
      if (museumId) {
        async function getMuseums() {
          const data = await fetchMuseums();
          if (data) {
            setMuseum(data);
    
            // Set placeholders
            setNama(data.nama || '');
            setLokasi(data.lokasi || '');
            setNoTelpon(data.no_telpon || '');
            setKeterangan(data.keterangan || '');
            setRating(data.rating || 0);
            setJumlahTiket(data.jumlah_tiket || 0);
            setTiketRegulerPrice(data.tiket_reguler_price || 0);
            setTiketPelajarPrice(data.tiket_pelajar_price || 0);
            setTiketKeluargaPrice(data.tiket_keluarga_price || 0);
          }
        }
    
        getMuseums(); 
      }
    }, [museumId]);
  
    async function fetchMuseums() {
      try {
        const response = await fetch("http://localhost:9090/museums/getSpec", {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
          },
          body: JSON.stringify({ id: museumId }), 
        });
  
        if (!response.ok) {
          throw new Error(`HTTP error! status: ${response.status}`);
        }
  
        const museum = await response.json();  
        console.log(museum);
        return museum;
      } catch (error) {
        console.error("Error fetching museum details:", error);
      }
    }

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();

    const museumData = {
      museum_id: museumId,
      nama,
      lokasi,
      no_telpon: noTelpon,
      keterangan,
      rating,
      jumlah_tiket: jumlahTiket,
      tiket_reguler_price: tiketRegulerPrice,
      tiket_pelajar_price: tiketPelajarPrice,
      tiket_keluarga_price: tiketKeluargaPrice,
    };

    try {
      const response = await fetch('http://localhost:9090/admins/EditMuseum', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(museumData),
      });

      if (response.ok) {
        console.log('Museum added successfully');
      } else {
        console.error('Failed to add museum');
      }
    } catch (error) {
      console.error('Error:', error);
    }
  };

  return (
    <div className="add-page">
      <div className="add-container">
        <div className="header">
          <div className="logo">
            Museum<span className="tix">Tix</span>
          </div>
          <h1>Edit Museum</h1>
          <p>Masukkan informasi museum yang ingin diubah</p>
        </div>
        <form onSubmit={handleSubmit}>
          <div className="form-group center">
            <label>Nama Museum:</label>
            <input
              type="text"
              value={nama}
              onChange={(e) => setNama(e.target.value)}
              required
            />
          </div>
          <div className="form-group left">
            <label>Lokasi Museum:</label>
            <input
              type="text"
              value={lokasi}
              onChange={(e) => setLokasi(e.target.value)}
              required
            />
          </div>
          <div className="form-group left">
            <label>No. Telpon Museum:</label>
            <input
              type="text"
              value={noTelpon}
              onChange={(e) => setNoTelpon(e.target.value)}
              required
            />
          </div>
          <div className="form-group left">
            <label>Keterangan Museum:</label>
            <textarea
              value={keterangan}
              onChange={(e) => setKeterangan(e.target.value)}
              required
            ></textarea>
          </div>
          <div className="form-row">
            <div className="form-group left">
              <label>Rating:</label>
              <input
                type="number"
                value={rating}
                onChange={(e) => setRating(Number(e.target.value))}
                required
                min="0"
                max="5"
                step="0.1"
                placeholder="e.g., 4.5"
              />
            </div>
            <div className="form-group left">
              <label>Jumlah Tiket:</label>
              <input
                type="number"
                value={jumlahTiket}
                onChange={(e) => setJumlahTiket(Number(e.target.value))}
                required
              />
            </div>
          </div>
          <div className="form-row">
            <div className="form-group left">
              <label>Harga Tiket Reguler:</label>
              <input
                type="number"
                value={tiketRegulerPrice}
                onChange={(e) => setTiketRegulerPrice(Number(e.target.value))}
                required
              />
            </div>
            <div className="form-group left">
              <label>Harga Tiket Pelajar:</label>
              <input
                type="number"
                value={tiketPelajarPrice}
                onChange={(e) => setTiketPelajarPrice(Number(e.target.value))}
                required
              />
            </div>
            <div className="form-group left">
              <label>Harga Tiket Keluarga:</label>
              <input
                type="number"
                value={tiketKeluargaPrice}
                onChange={(e) => setTiketKeluargaPrice(Number(e.target.value))}
                required
              />
            </div>
          </div>
          <div className="button-group">
            <button type="submit" className="add-button">Add</button>
            <button type="button" className="cancel-button">Cancel</button>
          </div>
        </form>
      </div>
    </div>
  );
};

export default Edit;
